version: '3.9'

volumes:
  postgres:

services:
  # app:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   profiles:
  #     - app
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env.docker

  # scheduler:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   command: node src/scheduler
  #   profiles:
  #     - app
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env.docker

  postgres:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
